############# Dutch navigation ##############

# main menu
[[main]]
name = "Overzicht"
pageRef = "/"
weight = 1

[[main]]
name = "Mis je iets?"
pageRef = "/info"
weight = 2

# [[main]]
# name = "Kroniek"
# pageRef = "/kroniek"
# weight = 2

# [[main]]
# weight = 4
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# pageRef = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# pageRef = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# pageRef = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# pageRef = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# pageRef = "/404"


# footer menu
[[footer]]
name = "Overzicht"
pageRef = "/"
weight = 1

[[footer]]
name = "Mis je iets?"
pageRef = "/info"
weight = 2


# [[footer]]
# name = "Privacy Policy"
# pageRef = "/privacy-policy"
# weight = 3
